### ISSUE TITLE
Error ao Compilar via terminal

### ISSUE THREAD

**Issue by vitordscosta** [DevelopersRede/magento2#3]
Boa tarde,

Estou utilizando o Magneto 2.3 com PHP 7.2, Quando executo o comando "bin/magento setup:di:compile" o processo e interrompido por um error na classe da rede.

Fatal error:  Class Rede\Adquirencia\Model\Rede\Interceptor may not inherit from final                                  class (Rede\Adquirencia\Model\Rede) in /var/www/html/store/generated/code/Rede/A                                 dquirencia/Model/Rede/Interceptor.php on line 7

**Comment by vitordscosta** [comment]
Esse mesmo erro acontece na versão 2.2.8 do Magento.

**Comment by viniqueiroz** [comment]
Corrigido na Versão 1.0.1

**Comment by vitordscosta** [comment]
Bom Dia, 

A versão 1.0.1 não esta disponível via composer?
