### ISSUE TITLE
Armazenando todos os dígitos do cartão no banco

### ISSUE THREAD

**Issue by Clayder** [DevelopersRede/magento2#6]
Atualmente o módulo está armazenando todos os dígitos do número do cartão na tabela sales_order_payment no campo cc_last_4. 

Por questões de segurança, o correto não seria salvar apenas os 4 últimos dígitos ? Realizei testes no ambiente (Environment) de teste e no de produção (realizando compras reais).

Reparei que na classe  Gateway/Response/CardDetailsHandler.php é setado o número do cartão no campo cc_last_4 sem realizar a filtragem. 

`$payment->setCcLast4($response_obj->getCardNumber());`

**Comment by netojoaobatista** [comment]
Seu `PR` foi mesclado. Obrigado!

**Comment by albertobraschi** [comment]
até hoje continua igual!
