### ISSUE TITLE
Packagist versão 1.0.1

### ISSUE THREAD

**Issue by vitordscosta** [DevelopersRede/magento2#8]
Bom dia,

Eu abri um issue sobre um erro ao compilar e me responderam com a correção na versão 1.0.1, porem essa versão não esta disponivel no packagist para instalar via composer.

Obrigado

**Comment by netojoaobatista** [comment]
Use a versão `1.1.0` porque ela corrige uma falha de segurança que permitia armazenar todos os dígitos do cartão.

`composer require developersrede/magento2:1.1.0`
